In [24]:
import pandas as pd
import requests
import re
import numpy as np
from datetime import datetime
import os

In [25]:
conflict_df = pd.read_csv('clean_conflict.csv')

In [26]:
conflict_df

,Unnamed: 0,conflictid,location,sidea,side b,sidebid,incomp,terr,year,intensity,cumint,type,start_month,ependdate,region,ISO2
0,0,200,Bolivia,Bolivia,Popular Revolutionary Movement,719,2,Bolivia,1946,2,1,3,7,1946-07-21,5,BO
1,1,200,Bolivia,Bolivia,MNR,720,2,Bolivia,1952,1,1,3,7,1952-04-12,5,BO
2,2,200,Bolivia,Bolivia,ELN,721,2,Bolivia,1967,1,1,3,7,1967-10-16,5,BO
3,3,201,Cambodia,France,Khmer Issarak,160,1,Cambodia,1946,1,0,1,8,NaN,3,KH
4,4,201,Cambodia,France,Khmer Issarak,160,1,Cambodia,1947,1,0,1,8,NaN,3,KH
5,5,201,Cambodia,France,Khmer Issarak,160,1,Cambodia,1948,1,0,1,8,NaN,3,KH
6,6,201,Cambodia,France,Khmer Issarak,160,1,Cambodia,1949,1,0,1,8,NaN,3,KH
7,7,201,Cambodia,France,Khmer Issarak,160,1,Cambodia,1950,1,0,1,8,NaN,3,KH
8,8,201,Cambodia,France,Khmer Issarak,160,1,Cambodia,1951,1,0,1,8,NaN,3,KH
9,9,201,Cambodia,France,Khmer Issarak,160,1,Cambodia,1952,1,0,1,8,NaN,3,KH
10,10,201,Cambodia,France,Khmer Issarak,160,1,Cambodia,1953,1,0,1,8,1953-11-09,3,KH
11,11,202,China,China,PLA,161,2,China,1946,2,1,3,12,NaN,3,CN
12,12,202,China,China,PLA,161,2,China,1947,2,1,3,12,NaN,3,CN
13,13,202,China,China,PLA,161,2,China,1948,2,1,3,12,NaN,3,CN
14,14,202,China,China,PLA,161,2,China,1949,2,1,3,12,1949-12-08,3,CN
15,15,203,Greece,Greece,DSE,162,2,Greece,1946,2,1,3,3,NaN,1,GR
16,16,203,Greece,Greece,DSE,162,2,Greece,1947,2,1,3,3,NaN,1,GR
17,17,203,Greece,Greece,DSE,162,2,Greece,1948,2,1,3,3,NaN,1,GR
18,18,203,Greece,Greece,DSE,162,2,Greece,1949,2,1,3,3,1949-10-16,1,GR
19,19,204,Indonesia,Netherlands,Indonesian People's Army,163,1,Indonesia,1946,1,0,1,10,NaN,3,ID
20,20,204,Indonesia,Netherlands,Indonesian People's Army,163,1,Indonesia,1947,1,0,1,10,NaN,3,ID
21,21,204,Indonesia,Netherlands,Indonesian People's Army,163,1,Indonesia,1948,1,0,1,10,NaN,3,ID
22,22,204,Indonesia,Netherlands,Indonesian People's Army,163,1,Indonesia,1949,1,0,1,10,1949-08-15,3,ID
23,23,205,Iran,Iran,KDPI,164,1,Kurdistan,1946,1,0,4,5,1946-12-16,2,IR
24,24,205,Iran,Iran,KDPI,164,1,Kurdistan,1966,1,1,3,5,NaN,2,IR
25,25,205,Iran,Iran,KDPI,164,1,Kurdistan,1967,1,1,3,5,NaN,2,IR
26,26,205,Iran,Iran,KDPI,164,1,Kurdistan,1968,1,1,3,5,1968-12-31,2,IR
27,27,205,Iran,Iran,KDPI,164,1,Kurdistan,1979,2,1,3,5,NaN,2,IR
28,28,205,Iran,Iran,KDPI,164,1,Kurdistan,1980,2,1,3,5,NaN,2,IR
29,29,205,Iran,Iran,KDPI,164,1,Kurdistan,1981,1,1,3,5,NaN,2,IR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,2247,13604,Syria,Syria,IS,234,1,Islamic State,2015,2,1,4,5,NaN,2,SY
2248,2248,13604,Syria,Syria,IS,234,1,Islamic State,2016,2,1,4,5,2016-12-31,2,SY
2249,2249,13611,Mali,Mali,FLM,6267,1,Macina Empire,2015,1,0,3,1,2015-10-28,4,ML
2250,2250,13637,Afghanistan,Afghanistan,IS,234,1,Islamic State,2015,1,0,4,2,NaN,3,AF
2251,2251,13637,Afghanistan,Afghanistan,IS,234,1,Islamic State,2016,2,1,4,2,2016-12-28,3,AF
2252,2252,13638,Cameroon,Cameroon,IS,234,1,Islamic State,2015,1,0,4,3,NaN,4,CM
2253,2253,13638,Cameroon,Cameroon,IS,234,1,Islamic State,2016,1,0,3,3,2016-10-06,4,CM
2254,2254,13639,Niger,Niger,IS,234,1,Islamic State,2015,1,0,4,3,NaN,4,NE
2255,2255,13639,Niger,Niger,IS,234,1,Islamic State,2016,1,0,4,3,2016-12-31,4,NE
2256,2256,13640,Chad,Chad,IS,234,1,Islamic State,2015,1,0,3,5,2015-11-01,4,TD
2257,2257,13641,Nigeria,Nigeria,IS,234,1,Islamic State,2015,2,1,4,3,NaN,4,NG
2258,2258,13641,Nigeria,Nigeria,IS,234,1,Islamic State,2016,2,1,4,3,2016-12-15,4,NG
2259,2259,13645,Yemen,Yemen (North Yemen),IS,234,1,Islamic State,2015,1,0,3,3,2015-10-06,2,YE
2260,2260,13646,Kenya,Kenya,Al-Shabaab,717,1,Northeastern Province and Coast,2015,1,0,3,3,NaN,4,KE
2261,2261,13646,Kenya,Kenya,Al-Shabaab,717,1,Northeastern Province and Coast,2016,1,0,3,3,2016-12-15,4,KE
2262,2262,13648,Egypt,Egypt,IS,234,1,Islamic State,2015,1,0,3,11,NaN,2,EG
2263,2263,13648,Egypt,Egypt,IS,234,1,Islamic State,2016,1,1,3,11,2016-12-06,2,EG
2264,2264,13653,India,India,UNLFW,6320,1,Western South East Asia,2015,1,0,3,4,NaN,3,IN
2265,2265,13653,India,India,UNLFW,6320,1,Western South East Asia,2016,1,0,3,4,2016-12-31,3,IN
2266,2266,13675,Lebanon,Lebanon,IS,234,1,Islamic State,2014,1,0,3,6,NaN,2,LB
2267,2267,13675,Lebanon,Lebanon,IS,234,1,Islamic State,2015,1,0,3,6,2015-12-15,2,LB
2268,2268,13692,"Afghanistan, United Kingdom, United States of ...",Afghanistan,"Government of United Kingdom, Government of Un...","28, 3",2,"Afghanistan, United Kingdom, United States of ...",2001,2,1,2,10,2001-11-13,"1, 3, 5",AF
2269,2269,13694,Libya,Libya,IS,234,1,Islamic State,2015,1,0,3,3,NaN,4,LY
2270,2270,13694,Libya,Libya,IS,234,1,Islamic State,2016,2,1,4,3,2016-12-07,4,LY
2271,2271,13721,Algeria,Algeria,Jund al-Khilafah,5870,1,Islamic State,2015,1,0,3,4,2015-05-20,4,DZ
2272,2272,13809,Syria,Syria,SDF,6288,3,Rojava Kurdistan,2016,1,0,3,12,2016-11-28,2,SY
2273,2273,13886,Jordan,Jordan,IS,234,1,Islamic State,2016,1,0,3,3,2016-12-29,2,JO
2274,2274,13902,Turkey,Turkey,IS,234,1,Islamic State,2015,1,0,3,7,NaN,2,TR
2275,2275,13902,Turkey,Turkey,IS,234,1,Islamic State,2016,2,1,3,7,NaN,2,TR
2276,2276,13936,Pakistan,Pakistan,IS,234,1,Islamic State,2016,1,0,3,2,2016-10-24,3,PK

In [27]:
years = conflict_df['year'].value_counts()

In [28]:
years_df = pd.DataFrame({'year':years.index, 'number_of_conflict':years.values})

In [29]:
years_df = years_df.sort_values('year')

In [30]:
years_df.to_csv('timeline.csv')