In [2]:
import pandas as pd
import requests
import re
import numpy as np

In [30]:
colonizer_countries = ['Denmark',
                         'France',
                         'Netherlands',
                         'Norway',
                         'Portugal',
                         'Russia',
                         'Spain',
                         'Sweden',
                         'Brandenburg',
                         'Britain',
                         'Courland',
                         'Denmark-Norway',
                         'Knights of Malta',
                         'Belgium',
                         'Germany',
                         'Italy',
                         'Austria',
                         'United Kingdom',
                         'Germany',
                         'Greece']

# UCDP Dataset

In [3]:
conflict_df = pd.read_csv('datasets/ucdp-prio-acd-171.csv')

In [5]:
conflict_df.head()

,conflictid,location,sidea,sidea2nd,side b,sidebid,sideb2nd,incomp,terr,year,...,epend,ependdate,ependprec,gwnoa,gwnoa2nd,gwnob,gwnob2nd,gwnoloc,region,version
0,200,Bolivia,Government of Bolivia,NaN,Popular Revolutionary Movement,719,NaN,2,NaN,1946,...,1,1946-07-21,1.0,145,NaN,NaN,NaN,145,5,17.1
1,200,Bolivia,Government of Bolivia,NaN,MNR,720,NaN,2,NaN,1952,...,1,1952-04-12,1.0,145,NaN,NaN,NaN,145,5,17.1
2,200,Bolivia,Government of Bolivia,NaN,ELN,721,NaN,2,NaN,1967,...,1,1967-10-16,1.0,145,NaN,NaN,NaN,145,5,17.1
3,201,Cambodia (Kampuchea),Government of France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1946,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
4,201,Cambodia (Kampuchea),Government of France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1947,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1

In [6]:
for index, row in conflict_df.iterrows():
    conflict_df.loc[index, 'location'] = re.sub(r'\([^)]*\)', '', conflict_df.loc[index, 'location'])
    conflict_df.loc[index, 'location'] = conflict_df.loc[index, 'location'].rstrip()
    conflict_df.loc[index, 'sidea'] = conflict_df.loc[index, 'sidea'].replace('Government of ', '')

In [7]:
conflict_df.head()

,conflictid,location,sidea,sidea2nd,side b,sidebid,sideb2nd,incomp,terr,year,...,epend,ependdate,ependprec,gwnoa,gwnoa2nd,gwnob,gwnob2nd,gwnoloc,region,version
0,200,Bolivia,Bolivia,NaN,Popular Revolutionary Movement,719,NaN,2,NaN,1946,...,1,1946-07-21,1.0,145,NaN,NaN,NaN,145,5,17.1
1,200,Bolivia,Bolivia,NaN,MNR,720,NaN,2,NaN,1952,...,1,1952-04-12,1.0,145,NaN,NaN,NaN,145,5,17.1
2,200,Bolivia,Bolivia,NaN,ELN,721,NaN,2,NaN,1967,...,1,1967-10-16,1.0,145,NaN,NaN,NaN,145,5,17.1
3,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1946,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
4,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1947,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1

In [86]:
countries_conflict_ucdp = conflict_df['location'].drop_duplicates()
countries_ucdp_without_colinizer_tmp = []

# Add all countries implicated in a conflict
for country in countries_conflict_ucdp:
    countries_ucdp_without_colinizer_tmp.extend(country.split(","))

# Remove spaces in country name
countries_ucdp_without_colinizer_tmp = [country.strip() for country in countries_ucdp_without_colinizer_tmp]
# Remove colonizer country
colonizer_countries.append('United States of America') # In a way, USA is a colonizer country... lolz
countries_ucdp_without_colinizer_tmp = [country for country in countries_ucdp_without_colinizer_tmp if country not in colonizer_countries]

# Remove duplicate
countries_ucdp_without_colinizer = set(countries_ucdp_without_colinizer_tmp)


countries_ucdp_without_colinizer

{'Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Azerbaijan',
 'Bangladesh',
 'Bolivia',
 'Bosnia-Herzegovina',
 'Brunei',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'DR Congo',
 'Djibouti',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Eritrea',
 'Ethiopia',
 'FYR',
 'Gabon',
 'Gambia',
 'Georgia',
 'Ghana',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Haiti',
 'Honduras',
 'Hungary',
 'Hyderabad',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Israel',
 'Ivory Coast',
 'Jordan',
 'Kenya',
 'Kuwait',
 'Laos',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Macedonia',
 'Madagascar',
 'Malaysia',
 'Mali',
 'Mauritania',
 'Mexico',
 'Moldova',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Nepal',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Oman',
 'Pakistan',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Rumania',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'South Vietnam',
 'South Yemen',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Uganda',
 'Ukraine',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zimbabwe'}

# Colonies extract from Wikipedia

In [88]:
colonies_conflict_df = pd.read_csv('datasets/colonies.csv')
colonised_countries_wikipedia = colonies_df['Colonized Country'].drop_duplicates()
colonised_countries_wikipedia = colonised_countries_wikipedia.tolist()

print("len(countries_ucdp_without_colinizer):", len(countries_ucdp_without_colinizer))
print("len(colonised_countries_wikipedia):", len(colonised_countries_wikipedia))

len(countries_ucdp_without_colinizer): 115
len(colonised_countries_wikipedia): 108

In [89]:
common_countries = []
unique_wiki = []
unique_ucpd = []

for colonised_country in countries_ucdp_without_colinizer:
    if colonised_country in colonised_countries_wikipedia:
        common_countries.append(colonised_country)
    else:
        unique_ucpd.append(colonised_country)
        
for colonised_country in colonised_countries_wikipedia:
    if colonised_country not in colonised_countries_ucdp:
        unique_wiki.append(colonised_country)
        
print("len(common_countries):", len(common_countries))

len(common_countries): 61

In [90]:
missing_colonies = [c for c in unique_ucpd if ',' not in c]
missing_colonies

['South Yemen',
 'Libya',
 'Albania',
 'Madagascar',
 'Syria',
 'Thailand',
 'Tunisia',
 'Nicaragua',
 'South Korea',
 'Gambia',
 'Serbia',
 'Ecuador',
 'Bolivia',
 'North Korea',
 'Hungary',
 'Colombia',
 'Paraguay',
 'Algeria',
 'Bosnia-Herzegovina',
 'Chile',
 'Afghanistan',
 'Ethiopia',
 'China',
 'FYR',
 'Papua New Guinea',
 'Comoros',
 'Argentina',
 'Macedonia',
 'Saudi Arabia',
 'Niger',
 'Venezuela',
 'Jordan',
 'Honduras',
 'Uruguay',
 'Trinidad and Tobago',
 'Eritrea',
 'Peru',
 'Grenada',
 'Lebanon',
 'Liberia',
 'Hyderabad',
 'Rumania',
 'Panama',
 'Congo',
 'South Vietnam',
 'Guatemala',
 'South Sudan',
 'DR Congo',
 'Nepal',
 'Australia',
 'Mexico',
 'Turkey',
 'Iran',
 'Croatia']

In [91]:
unique_wiki

['Greenland',
 'Iceland',
 'Canada',
 'Haiti',
 'Benin',
 'Cameroon',
 'Chad',
 'Central African Republic',
 'Guinea',
 'Burkina Faso',
 'Djibouti',
 'Mali',
 'Togo',
 'Gabon',
 'Ivory Coast',
 'Mauritania',
 'Morocco',
 'Republic of Tunisia',
 'Mauritius',
 'Cambodia',
 'Laos',
 'Vietnam',
 'Vanuatu',
 'Guyana',
 'Suriname',
 'South Africa',
 'Ghana',
 'Republic of Angola',
 'Senegal',
 'Iraq',
 'Bangladesh',
 'Indonesia',
 'Taiwan',
 'Brazil',
 'Cisplatina (Uruguay)',
 'French Guiana',
 'Angola',
 'Cabinda',
 'Cape Verde',
 'Nigeria',
 'Mozambique',
 'Guinea-Bissau',
 'Goa',
 'East Timor',
 'Kazakhstan',
 'Kyrgyzstan',
 'Tajikistan',
 'Turkmenistan',
 'Uzbekistan',
 'Belarus',
 'Estonia',
 'Latvia',
 'Lithuania',
 'Moldova',
 'Ukraine',
 'Georgia',
 'Azerbaijan',
 'Costa Rica',
 'El Salvador',
 'Cuba',
 'Dominican Republic',
 'Jamaica',
 'Argentine Republic',
 'Equatorial Guinea',
 'Philippines',
 'Falkland Islands',
 'Sudan',
 'Lesotho',
 'Botswana',
 'Kenya',
 'Somalia',
 'Egypt',
 'The Gambia',
 'Federal Republic of Nigeria',
 'Zambia',
 'Malawi',
 'Sierra Leone',
 'Namibia',
 'Zimbabwe',
 'Swaziland',
 'Tanzania',
 'Uganda',
 'Yemen',
 'Kuwait',
 'Oman',
 'Israel',
 'Qatar',
 'Hashemite Kingdom of Transjordan',
 'United Arab Emirates',
 'India',
 'Pakistan',
 'Myanmar',
 'Sri Lanka',
 'Corsica',
 'Cyprus',
 'Ireland',
 'Democratic Republic of the Congo',
 'Republic of Burundi',
 'Rwanda',
 'Burundi',
 'Saarland',
 'Solomon Islands',
 'Brunei',
 'New Zealand',
 'Malaysia',
 'Independent State of Papua New Guinea',
 'Samoa',
 'Hong Kong']