In [41]:
import pandas as pd
import requests
import re
import numpy as np

In [42]:
colonizer_countries = ['Denmark',
                         'France',
                         'Netherlands',
                         'Norway',
                         'Portugal',
                         'Russia',
                         'Spain',
                         'Sweden',
                         'Brandenburg',
                         'Britain',
                         'Courland',
                         'Denmark-Norway',
                         'Knights of Malta',
                         'Belgium',
                         'Germany',
                         'Italy',
                         'Austria',
                         'United Kingdom',
                         'Germany',
                         'Greece']

# UCDP Dataset

In [57]:
conflict_df = pd.read_csv('datasets/ucdp-prio-acd-171.csv')

In [56]:
for country in range(len(conflict_df))

,conflictid,location,sidea,sidea2nd,side b,sidebid,sideb2nd,incomp,terr,year,...,epend,ependdate,ependprec,gwnoa,gwnoa2nd,gwnob,gwnob2nd,gwnoloc,region,version
0,200,Bolivia,Bolivia,NaN,Popular Revolutionary Movement,719,NaN,2,NaN,1946,...,1,1946-07-21,1.0,145,NaN,NaN,NaN,145,5,17.1
1,200,Bolivia,Bolivia,NaN,MNR,720,NaN,2,NaN,1952,...,1,1952-04-12,1.0,145,NaN,NaN,NaN,145,5,17.1
2,200,Bolivia,Bolivia,NaN,ELN,721,NaN,2,NaN,1967,...,1,1967-10-16,1.0,145,NaN,NaN,NaN,145,5,17.1
3,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1946,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
4,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1947,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
5,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1948,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
6,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1949,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
7,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1950,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
8,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1951,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
9,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1952,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
10,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1953,...,1,1953-11-09,1.0,220,NaN,NaN,NaN,811,3,17.1
11,202,China,China,NaN,PLA,161,NaN,2,NaN,1946,...,0,NaN,NaN,710,NaN,NaN,NaN,710,3,17.1
12,202,China,China,NaN,PLA,161,NaN,2,NaN,1947,...,0,NaN,NaN,710,NaN,NaN,NaN,710,3,17.1
13,202,China,China,NaN,PLA,161,NaN,2,NaN,1948,...,0,NaN,NaN,710,NaN,NaN,NaN,710,3,17.1
14,202,China,China,NaN,PLA,161,NaN,2,NaN,1949,...,1,1949-12-08,1.0,710,NaN,NaN,NaN,710,3,17.1
15,203,Greece,Greece,NaN,DSE,162,NaN,2,NaN,1946,...,0,NaN,NaN,350,NaN,NaN,NaN,350,1,17.1
16,203,Greece,Greece,NaN,DSE,162,NaN,2,NaN,1947,...,0,NaN,NaN,350,NaN,NaN,NaN,350,1,17.1
17,203,Greece,Greece,NaN,DSE,162,NaN,2,NaN,1948,...,0,NaN,NaN,350,NaN,NaN,NaN,350,1,17.1
18,203,Greece,Greece,NaN,DSE,162,NaN,2,NaN,1949,...,1,1949-10-16,1.0,350,NaN,NaN,NaN,350,1,17.1
19,204,Indonesia,Netherlands,NaN,Indonesian People's Army,163,NaN,1,Indonesia,1946,...,0,NaN,NaN,210,NaN,NaN,NaN,850,3,17.1
20,204,Indonesia,Netherlands,NaN,Indonesian People's Army,163,NaN,1,Indonesia,1947,...,0,NaN,NaN,210,NaN,NaN,NaN,850,3,17.1
21,204,Indonesia,Netherlands,NaN,Indonesian People's Army,163,NaN,1,Indonesia,1948,...,0,NaN,NaN,210,NaN,NaN,NaN,850,3,17.1
22,204,Indonesia,Netherlands,NaN,Indonesian People's Army,163,NaN,1,Indonesia,1949,...,1,1949-08-15,1.0,210,NaN,NaN,NaN,850,3,17.1
23,205,Iran,Iran,NaN,KDPI,164,Government of Russia (Soviet Union),1,Kurdistan,1946,...,1,1946-12-16,1.0,630,NaN,NaN,365,630,2,17.1
24,205,Iran,Iran,NaN,KDPI,164,NaN,1,Kurdistan,1966,...,0,NaN,NaN,630,NaN,NaN,NaN,630,2,17.1
25,205,Iran,Iran,NaN,KDPI,164,NaN,1,Kurdistan,1967,...,0,NaN,NaN,630,NaN,NaN,NaN,630,2,17.1
26,205,Iran,Iran,NaN,KDPI,164,NaN,1,Kurdistan,1968,...,1,1968-12-31,5.0,630,NaN,NaN,NaN,630,2,17.1
27,205,Iran,Iran,NaN,KDPI,164,NaN,1,Kurdistan,1979,...,0,NaN,NaN,630,NaN,NaN,NaN,630,2,17.1
28,205,Iran,Iran,NaN,KDPI,164,NaN,1,Kurdistan,1980,...,0,NaN,NaN,630,NaN,NaN,NaN,630,2,17.1
29,205,Iran,Iran,NaN,KDPI,164,NaN,1,Kurdistan,1981,...,0,NaN,NaN,630,NaN,NaN,NaN,630,2,17.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,13604,Syria,Syria,"Government of Iran, Government of Russia (Sovi...",IS,234,NaN,1,Islamic State,2015,...,0,NaN,NaN,652,"630, 365",NaN,NaN,652,2,17.1
2248,13604,Syria,Syria,"Government of Iran, Government of Russia (Sovi...",IS,234,NaN,1,Islamic State,2016,...,1,2016-12-31,1.0,652,"630, 365",NaN,NaN,652,2,17.1
2249,13611,Mali,Mali,NaN,FLM,6267,NaN,1,Macina Empire,2015,...,1,2015-10-28,1.0,432,NaN,NaN,NaN,432,4,17.1
2250,13637,Afghanistan,Afghanistan,"Government of Pakistan, Government of United S...",IS,234,NaN,1,Islamic State,2015,...,0,NaN,NaN,700,"770, 2",NaN,NaN,700,3,17.1
2251,13637,Afghanistan,Afghanistan,"Government of Pakistan, Government of United S...",IS,234,NaN,1,Islamic State,2016,...,1,2016-12-28,1.0,700,"770, 2",NaN,NaN,700,3,17.1
2252,13638,Cameroon,Cameroon,Government of Chad,IS,234,NaN,1,Islamic State,2015,...,0,NaN,NaN,471,483,NaN,NaN,471,4,17.1
2253,13638,Cameroon,Cameroon,NaN,IS,234,NaN,1,Islamic State,2016,...,1,2016-10-06,1.0,471,NaN,NaN,NaN,471,4,17.1
2254,13639,Niger,Niger,Government of Chad,IS,234,NaN,1,Islamic State,2015,...,0,NaN,NaN,436,483,NaN,NaN,436,4,17.1
2255,13639,Niger,Niger,"Government of Chad, Government of Nigeria",IS,234,NaN,1,Islamic State,2016,...,1,2016-12-31,1.0,436,"483, 475",NaN,NaN,436,4,17.1
2256,13640,Chad,Chad,NaN,IS,234,NaN,1,Islamic State,2015,...,1,2015-11-01,1.0,483,NaN,NaN,NaN,483,4,17.1
2257,13641,Nigeria,Nigeria,"Government of Cameroon, Government of Chad, Go...",IS,234,NaN,1,Islamic State,2015,...,0,NaN,NaN,475,"471, 483, 436",NaN,NaN,475,4,17.1
2258,13641,Nigeria,Nigeria,"Government of Cameroon, Government of Chad, Go...",IS,234,NaN,1,Islamic State,2016,...,1,2016-12-15,1.0,475,"471, 483, 436",NaN,NaN,475,4,17.1
2259,13645,Yemen,Yemen (North Yemen),NaN,IS,234,NaN,1,Islamic State,2015,...,1,2015-10-06,1.0,678,NaN,NaN,NaN,678,2,17.1
2260,13646,Kenya,Kenya,NaN,Al-Shabaab,717,NaN,1,Northeastern Province and Coast,2015,...,0,NaN,NaN,501,NaN,NaN,NaN,501,4,17.1
2261,13646,Kenya,Kenya,NaN,Al-Shabaab,717,NaN,1,Northeastern Province and Coast,2016,...,1,2016-12-15,1.0,501,NaN,NaN,NaN,501,4,17.1
2262,13648,Egypt,Egypt,NaN,IS,234,NaN,1,Islamic State,2015,...,0,NaN,NaN,651,NaN,NaN,NaN,651,2,17.1
2263,13648,Egypt,Egypt,NaN,IS,234,NaN,1,Islamic State,2016,...,1,2016-12-06,2.0,651,NaN,NaN,NaN,651,2,17.1
2264,13653,India,India,NaN,UNLFW,6320,NaN,1,Western South East Asia,2015,...,0,NaN,NaN,750,NaN,NaN,NaN,750,3,17.1
2265,13653,India,India,NaN,UNLFW,6320,NaN,1,Western South East Asia,2016,...,1,2016-12-31,1.0,750,NaN,NaN,NaN,750,3,17.1
2266,13675,Lebanon,Lebanon,NaN,IS,234,NaN,1,Islamic State,2014,...,0,NaN,NaN,660,NaN,NaN,NaN,660,2,17.1
2267,13675,Lebanon,Lebanon,NaN,IS,234,NaN,1,Islamic State,2015,...,1,2015-12-15,1.0,660,NaN,NaN,NaN,660,2,17.1
2268,13692,"Afghanistan, United Kingdom, United States of ...",Afghanistan,NaN,"Government of United Kingdom, Government of Un...","28, 3",NaN,2,NaN,2001,...,1,2001-11-13,2.0,700,NaN,"2, 200",NaN,"2, 200, 700","1, 3, 5",17.1
2269,13694,Libya,Libya,NaN,IS,234,NaN,1,Islamic State,2015,...,0,NaN,NaN,620,NaN,NaN,NaN,620,4,17.1
2270,13694,Libya,Libya,Government of United States of America,IS,234,NaN,1,Islamic State,2016,...,1,2016-12-07,2.0,620,2,NaN,NaN,620,4,17.1
2271,13721,Algeria,Algeria,NaN,Jund al-Khilafah,5870,NaN,1,Islamic State,2015,...,1,2015-05-20,1.0,615,NaN,NaN,NaN,615,4,17.1
2272,13809,Syria,Syria,NaN,SDF,6288,NaN,3,Rojava Kurdistan,2016,...,1,2016-11-28,1.0,652,NaN,NaN,NaN,652,2,17.1
2273,13886,Jordan,Jordan,NaN,IS,234,NaN,1,Islamic State,2016,...,1,2016-12-29,1.0,663,NaN,NaN,NaN,663,2,17.1
2274,13902,Turkey,Turkey,NaN,IS,234,NaN,1,Islamic State,2015,...,0,NaN,NaN,640,NaN,NaN,NaN,640,2,17.1
2275,13902,Turkey,Turkey,NaN,IS,234,NaN,1,Islamic State,2016,...,0,NaN,NaN,640,NaN,NaN,NaN,640,2,17.1
2276,13936,Pakistan,Pakistan,NaN,IS,234,NaN,1,Islamic State,2016,...,1,2016-10-24,1.0,770,NaN,NaN,NaN,770,3,17.1

In [45]:
for index, row in conflict_df.iterrows():
    conflict_df.loc[index, 'location'] = re.sub(r'\([^)]*\)', '', conflict_df.loc[index, 'location'])
    conflict_df.loc[index, 'location'] = conflict_df.loc[index, 'location'].rstrip()
    conflict_df.loc[index, 'sidea'] = conflict_df.loc[index, 'sidea'].replace('Government of ', '')

In [46]:
conflict_df.head()

,conflictid,location,sidea,sidea2nd,side b,sidebid,sideb2nd,incomp,terr,year,...,epend,ependdate,ependprec,gwnoa,gwnoa2nd,gwnob,gwnob2nd,gwnoloc,region,version
0,200,Bolivia,Bolivia,NaN,Popular Revolutionary Movement,719,NaN,2,NaN,1946,...,1,1946-07-21,1.0,145,NaN,NaN,NaN,145,5,17.1
1,200,Bolivia,Bolivia,NaN,MNR,720,NaN,2,NaN,1952,...,1,1952-04-12,1.0,145,NaN,NaN,NaN,145,5,17.1
2,200,Bolivia,Bolivia,NaN,ELN,721,NaN,2,NaN,1967,...,1,1967-10-16,1.0,145,NaN,NaN,NaN,145,5,17.1
3,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1946,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1
4,201,Cambodia,France,NaN,Khmer Issarak,160,NaN,1,Cambodia,1947,...,0,NaN,NaN,220,NaN,NaN,NaN,811,3,17.1

In [63]:
countries_conflict_ucdp = conflict_df['location'].drop_duplicates()
countries_ucdp_without_colinizer_tmp = []

# Add all countries implicated in a conflict
for country in countries_conflict_ucdp:
    countries_ucdp_without_colinizer_tmp.extend(country.split(","))

# Remove spaces in country name
countries_ucdp_without_colinizer_tmp = [country.strip() for country in countries_ucdp_without_colinizer_tmp]
# Remove colonizer country
colonizer_countries.append('United States of America') # In a way, USA is a colonizer country... lolz
countries_ucdp_without_colinizer_tmp = [country for country in countries_ucdp_without_colinizer_tmp if country not in colonizer_countries]

# Remove duplicate
countries_ucdp_without_colinizer = set(countries_ucdp_without_colinizer_tmp)


countries_ucdp_without_colinizer;

### Addition of country ID to the UCDP datasets

In [66]:
countries_codes = pd.read_csv('datasets/countries_codes_and_coordinates.csv')
countries_codes.head()

          Country ISO2 ISO3  NumericCode  Latitude  Longitude
0     Afghanistan   AF  AFG            4   33.0000       65.0
1         Albania   AL  ALB            8   41.0000       20.0
2         Algeria   DZ  DZA           12   28.0000        3.0
3  American Samoa   AS  ASM           16  -14.3333     -170.0
4         Andorra   AD  AND           20   42.5000        1.6

In [88]:
country = conflict_df.loc[1, 'location'] 
countries_codes.get_value[countries_codes['Country']==country]

    Country ISO2 ISO3  NumericCode  Latitude  Longitude lol (1, lol)
26  Bolivia   BO  BOL           68     -17.0      -65.0  BO       BO

# Colonies extract from Wikipedia

In [48]:
colonies_wikipedia_df = pd.read_csv('datasets/colonies_wikipedia.csv', ',')
colonized_countries_wikipedia = colonies_wikipedia_df['Colonized Country'].drop_duplicates()
colonized_countries_wikipedia = colonized_countries_wikipedia.tolist()

print("len(countries_ucdp_without_colinizer):", len(countries_ucdp_without_colinizer))
print("len(colonized_countries_wikipedia):", len(colonized_countries_wikipedia))

len(countries_ucdp_without_colinizer): 115
len(colonized_countries_wikipedia): 137

In [49]:
colonies_wikipedia_df.head()

,Unnamed: 0,Colonized Country,ID,Date,Colonizer Country,URL
0,1,Greenland,GL,False,False,/wiki/Greenland
1,2,Iceland,IS,False,False,/wiki/Iceland
2,3,Canada,CA,1867,United Kingdom,/wiki/Canada
3,4,United States,US,1776,Britain,/wiki/United_States
4,5,Haiti,HT,1804,France,/wiki/Haiti

In [50]:
common_countries = []
unique_wiki = []
unique_ucpd = []

for colonized_country in countries_ucdp_without_colinizer:
    if colonized_country in colonized_countries_wikipedia:
        common_countries.append(colonized_country)
    else:
        unique_ucpd.append(colonized_country)
        
for colonized_country in colonized_countries_wikipedia:
    if colonized_country not in countries_ucdp_without_colinizer:
        unique_wiki.append(colonized_country)
        
print("len(common_countries):", len(common_countries))

len(common_countries): 81

In [55]:
missing_colonies = [c for c in unique_ucpd if ',' not in c]
missing_colonies

['Tunisia',
 'Bosnia-Herzegovina',
 'Turkey',
 'Hungary',
 'Nicaragua',
 'Peru',
 'Lebanon',
 'Afghanistan',
 'Hyderabad',
 'South Korea',
 'Serbia',
 'Macedonia',
 'Guatemala',
 'Papua New Guinea',
 'Paraguay',
 'Iran',
 'Syria',
 'FYR',
 'Albania',
 'Liberia',
 'Niger',
 'Honduras',
 'South Vietnam',
 'Venezuela',
 'Uruguay',
 'Congo',
 'South Yemen',
 'Rumania',
 'North Korea',
 'Gambia',
 'Grenada',
 'Trinidad and Tobago',
 'Nepal',
 'Thailand']

In [52]:
unique_wiki

['Greenland',
 'Iceland',
 'Canada',
 'United States',
 'Benin',
 'Republic of the Congo',
 'French Southern and Antarctic Lands',
 'Republic of Tunisia',
 'Mauritius',
 'British Indian Ocean Territory',
 'Vanuatu',
 'Guyana',
 'Brazil',
 'Gold Coast',
 'Brong-Ahafo',
 'Central region',
 'Cisplatina (Uruguay)',
 'French Guiana',
 'Cabinda',
 'Cape Verde',
 'Goa',
 'East Timor',
 'Kazakhstan',
 'Kyrgyzstan',
 'Turkmenistan',
 'Belarus',
 'Estonia',
 'Latvia',
 'Lithuania',
 'Bahamas',
 'Belize',
 'Jamaica',
 'Equatorial Guinea',
 'Luxembourg',
 nan,
 'Falkland Islands',
 'Namibia',
 'Botswana',
 'Poland',
 'Palestine',
 'The Gambia',
 'Zambia',
 'Malawi',
 'Swaziland',
 'United Arab Emirates',
 'Qatar',
 'Ireland',
 'Slovenia',
 'Montenegro',
 'Saarland',
 'Solomon Islands',
 'Fiji',
 'New Zealand',
 'Independent State of Papua New Guinea',
 'Samoa',
 'Hong Kong']